version: "3.3"

services:
  alist:
    image: xhofe/alist:latest
    container_name: alist
    environment:
      - PUID=0
      - PGID=0
      - TZ=UTC # specify a timezone to use,
      - UMASK=022
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/etc/alist:/opt/alist/data
    ports:
      - 5244:5244
      - 5245:5245
    restart: unless-stopped
    #networks:
    #  - proxy
    #labels:
    #  - traefik.enable=true
    #  - traefik.docker.network=proxy
    #  - traefik.http.routers.calibre.rule=Host(`calibre.example.com`)
    #  - traefik.http.services.calibre.loadbalancer.server.port=8083
    #  # Optional part for traefik middlewares
    #  - traefik.http.routers.calibre.middlewares=local-ipwhitelist@file,authelia@docker

#networks:
#  proxy:
#    external: true
