services:

  duplicati:
    image: linuxserver/duplicati:latest
    container_name: duplicati
    hostname: duplicati
    entrypoint:
      - /init
    ports:
      - 8200:8200 # MGMT UI
    expose:
      - 8200
    environment:
      - PUID=0
      - PGID=1000
      - TZ=Europe/Berlin
    restart: unless-stopped
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/duplicati/backups:/backups
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/duplicati/config:/config
      - /path/to/my/data/to/backup:/source # change this
    #networks:
    #  - proxy
    #labels:
    #  - com.centurylinklabs.watchtower.enable=false
    #  - traefik.enable=true
    #  - traefik.http.routers.duplicati.rule=Host(`duplicati.example.com`)
    #  - traefik.http.services.duplicati.loadbalancer.server.port=8200
    #  - traefik.docker.network=proxy
    #  # Part for local lan services only
    #  - traefik.http.routers.duplicati.middlewares=local-ipwhitelist@file

#networks:
#  proxy:
#     external: true
    
