services:

  gitea:
    image: gitea/gitea:latest    
    container_name: gitea
    restart: unless-stopped    
    environment:
      - USER_UID=1000
      - USER_GID=1000
    hostname: gitea
    ports:
      - 3000:3000 #webgui
      - 2222:22 #ssh
    expose:
      - 3000
      - 22
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/gitea/data:/data
    #networks:
    #  - proxy
    #labels:
    #  - traefik.enable=true
    #  - traefik.http.routers.gitea.rule=Host(`git.example.com`)
    #  - traefik.http.services.gitea.loadbalancer.server.port=3000
    #  - traefik.docker.network=proxy
    #  # Part for local lan services only
    #  - traefik.http.routers.gitea.middlewares=local-ipwhitelist@file

#networks:
#  proxy:
#    external: true
