services:

  npm:
    image: jc21/nginx-proxy-manager:latest    
    container_name: npm
    hostname: npm    
    environment:
      - TZ=Europe/Berlin
      - PUID=1000 # see https://nginxproxymanager.com/advanced-config/
      - PGID=1000 # see https://nginxproxymanager.com/advanced-config/
    ports:
      - 80:80/tcp # HTTP
      - 443:443/tcp # HTTPS
      - 81:81/tcp # MGMT UI, do not expose publicly
    expose:
      - 80
      - 443
      - 81
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 30s
      timeout: 3s
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/nginx-proxy-manager/data:/data
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    #networks:
    #  - npm_proxy

#networks:
#  npm_proxy:
#    external: true
