services:

  homeassistant:
    image: linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    restart: unless-stopped    
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ${DOCKER_VOLUME_STORAGE:-/mnt/docker-volumes}/homeassistant/config:/config
    #ports:
    #  - 8123:8123 # optional of host network is used
    #devices:
    #  - /path/to/device:/path/to/device #optional