# general
appname = casdoor
httpport = 8000
runmode = prod

# database
driverName = postgres
dataSourceName = host=db port=5432 user=casdoor password=pls-changeme-to-strong-pw dbname=casdoor sslmode=disable

# logging and debugging
showSql = true
logPostOnly = true

# more settings
verificationCodeTimeout = 10
inactiveTimeoutMinutes = 10
staticBaseUrl = "https://cdn.casbin.org"
enableGzip = true
